apiVersion: apps/v1
kind: Deployment
metadata:
  name: mean-client-ang
  labels:
    app: mean-client-ang
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mean-client-ang
  template:
    metadata:
      labels:
        app: mean-client-ang
    spec:
      containers:
        - name: mean-client-ang
          image: localhost:32000/mean-client-angula:local
          ports:
            - containerPort: 4200
          # env:
          #   - name: API_URL
          #     valueFrom:
          #       configMapKeyRef:
          #         key: api_url
          #         name: econfigmap

--- 
apiVersion: v1
kind: Service
metadata:
  name: mean-client-ang
spec:
  selector:
    app: mean-client-ang
  type: NodePort
  ports:
    - protocol: TCP
      port: 4200
      targetPort: 4200

